#!/usr/bin/env ruby
#encoding: utf-8

require 'yaml'
require 'em-zeromq'

config = YAML.load_file 'config.yml'
server_conf = config['server']
host = server_conf['host']
port = server_conf['port']

zmq = EM::ZeroMQ::Context.new(1)

EM.run do
	push = zmq.socket(ZMQ::PUSH)
	push.connect("tcp://#{host}:#{port}")

	EM.add_periodic_timer(1) {
		push.send_msg("Hello")
	}
end
